### ISSUE TITLE
remove metadata from the doc

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel-platform#59]
Barrel metadata of a document should never be added to the document by the user. Instead they should be sent via an header.

### TODO:

- [x] make the revision optionnal
- [x] handle `_rev` via the "ETag" header on PUT, DELETE. 
- [x] send ETag header on GET and HEAD request
- [x] don't support `_deleted: true` property on put

### NOTES:

* E-Tag is required when sending a revision (for replication purpose) 
* E-Tag is optional on PUT/DELETE. When a revision is not given, the last winning revision on the server will be used as parent. (LWW).

**Comment by benoitc** [comment]
As discussed, I am making a more detailed description of the changes.

Places to look are the following:

### core: 

- [barrel_local:put/3](https://github.com/barrel-db/barrel-platform/blob/master/apps/barrel_store/src/barrel_local.erl#L178) should take a `rev` setting in Options instead of parsing it in  `barrel_doc:doc_from_obj/1` from the obj. Following that change `barrel_doc:doc_from_obj/1` should become `barrel_doc:make_doc(Obj, Revs, Deleted)`  . Deleted is always true for `barrel_local:put/3` while it will be set to the value given for `barrel_local:put_rev`. 
- [barrel_local:put_rev](https://github.com/barrel-db/barrel-platform/blob/master/apps/barrel_store/src/barrel_local.erl#L186-L197) should become `put_rev(Db, Doc, History, Deleted, Options)` to allows someone to pass the Deletion option
- `barrel_local:delete`shoudl create a `#doc{}` with an object w but deleted  to true, ids and rev set .

> we should probably have a `barrel_db:delete` function that do this job. but unsure

- [barrel_doc:revid](https://github.com/barrel-db/barrel-platform/blob/master/apps/barrel_common/src/barrel_doc.erl#L38)  used in [the merge function:](https://github.com/barrel-db/barrel-platform/blob/master/apps/barrel_store/src/barrel_db.erl#L832) should be modified so we can pass Deleted outside of the doc and include it in the hash instead of having it added to the doc as a `_deleted` property. Hash should now be hash([BinPos, Parent, Body, Deleted]) . While we are here we should not used `term_to_binary(Body)  but `jsx:encode(Body)`. Indeed each of the hash values should be valid JSON values so we can handle hashes in various languages.

### HTTP api

- barrel_http handlers should use the new api above
- barrel_httpc module functions' signatures should look like the signatures in barrel_local

### Replication

- `put_rev` in [barrel_replicate/src/barrel_replicate_alg.erl](https://github.com/barrel-db/barrel-platform/blob/master/apps/barrel_replicate/src/barrel_replicate_alg.erl#L79-L82) should be edited to extract the `_deleted` setting from the doc previously fetched.

**Comment by benoitc** [comment]
Things i'm not sure yet, is how to handle the special delete case when retrieving the revisions. Should we append it to the body like now? Seems good for me. What could be the other way to know it if not done that way?

**Comment by BernardNotarianni** [comment]
## Plan

**Core**
- [ ] refactor `barrel_local:put` 
- [ ] refactor `barrel_local:put_put`
- [ ] refactor `barrel_local:delete`
- [ ] refactor `barrel_doc:revid`

**HTTP API**
- [ ] refactor barrel_http handlers
- [ ] refactor barrel_httpc

**Replication**
- [ ] refactor `barrel_replicate_alg:put_rev`

**Comment by BernardNotarianni** [comment]
@benoitc questions for you:

1) Should we modify also `barrel_local:get` to return the doc without `_rev` and `_deleted` included?
If yes, I guess they should be returned in the tuple, like `{ok, Doc, RevId, Deleted}`. Correct?

2) What should happen if I dont include a `{rev, RevId}` options for `barrel_local:put` ?
I guess we should currently throw an error, and maybe later add an option like `{rev, lastone}` which would force the write, whatever the last revision. though?

**Comment by BernardNotarianni** [comment]
@benoitc some corrolary question:

3. What about the HTTP API for docs? Should we still include the `_rev` and `_deleted` props in the documents, or should we adapt it to comply with this new `barrel_local` api for docs?
Maybe it depends how we can handle an incremental modification, or not... 🤔

**Comment by benoitc** [comment]
1. Right. I would only keep the metadata in the JSON. Then `barrel_replicate_alg:get` need also be edited and so barrel_indexer.

2. Right now there is no need to throw any error. It will return a conflict update if the revision is not given.

**Comment by BernardNotarianni** [comment]
> I would only keep the metadata in the JSON

You mean we should keep the metadata in the JSON handled by the HTTP API?

**Comment by benoitc** [comment]
Looking more closely at the related  [barrel_indexer](https://github.com/barrel-db/barrel-platform/blob/master/apps/barrel_store/src/barrel_indexer.erl#L230-L247) code. It seems we should also have a way to retrieve the resource id. Maybe the signature should rather be : `{ok, Doc, Meta}` ? Where `Meta` is a `map` ?

**Comment by benoitc** [comment]
>> I would only keep the metadata in the JSON
> You mean we should keep the metadata in the JSON handled by the HTTP API?

yes

**Comment by BernardNotarianni** [comment]
I am afraid `{ok, Doc, RevId, Deleted}` is a bit verbose as a return value for `barrel_local:get`. I see those options:
1. `{ok, Doc, RevId, Deleted}`
2. `#{ok, #{doc => Doc, revid=> RevId, deleted => Deleted}`
3. `{ok, Doc} = barrel_local:get(DocId, [])`
    `{ok, Doc} = barrel_local:get(DocId, [{info, rev}])`
    `{ok, Doc, RevId, Deleted} = barrel_local:get(DocId, [{info, full}])`

**Comment by benoitc** [comment]
@BernardNotarianni I agree, I proposed `{ok, Doc, Meta}` which sounds correct . Meta are always fetched with the doc so there is no reason to make them optional in the internal return.

**Comment by BernardNotarianni** [comment]
## Plan

**Core**
- [ ] refactor `barrel_local:get` 
- [ ] refactor `barrel_local:put` 
- [ ] refactor `barrel_local:put_put`
- [ ] refactor `barrel_local:delete`
- [ ] refactor `barrel_doc:revid`

**HTTP API**
- [ ] refactor barrel_http handlers
- [ ] refactor barrel_httpc

**Replication**
- [ ] refactor `barrel_replicate_alg:put_rev`

**Comment by benoitc** [comment]
@BernardNotarianni don't forget `barrel_indexer:analyze` if you change the `barrel_local:get` return also :)

**Comment by BernardNotarianni** [comment]
## Plan
New plan, organized to refactor vertically in order to have all tests working again at each steps.

**refactor `barrel_local:get` **
- [ ] core
- [ ] replicate
- [ ] http
- [ ] httpc

**refactor `barrel_local:put_rev` **
- [ ] core
- [ ] replicate
- [ ] http
- [ ] httpc

**refactor `barrel_local:delete`**
- [ ] core
- [ ] replicate
- [ ] http
- [ ] httpc

** refactor `barrel_doc:revid` **
- [ ] core
- [ ] replicate
- [ ] http
- [ ] httpc

**Comment by BernardNotarianni** [comment]
PUT will now take an extra header E-Tag to get the revision it is updating and DELETE the same.

**Comment by benoitc** [comment]
the HTTP api for `put_revs is currently accepting :

```erlang
#{
  <<"document">> => Doc,
  <<"history">> => History
}
```

I propose to add the `rev` and `deleted` properties to it since the doc doesn't contain these infos anymore .

**Comment by benoitc** [comment]
in fact only deleted is useful there.

**Comment by benoitc** [comment]
also since we don't use "_deleted" in the doc to signal an update I propose to only handle delete on the `DELETE` request:

```
DELETE /dbs/<dbname>/docid
E-Tag: somerevision
```

Thoughts?

**Comment by benoitc** [comment]
header is **ETag** btw. I made a mistake :)

**Comment by benoitc** [comment]
To be consistent in our API `POST` should only allow doc creation. Ie until the header `x-barrel-is-upsert: true` is given, if a document is  sent with an already existing `id`, an error should be returned. cc @BernardNotarianni

**Comment by benoitc** [comment]
As requested, here is a quick summary of the changes needed in the HTTP API to help us to finish the current work. Let me know if I forgot something.

* POST /<dbs>/docs

* if no id is given, an id will be created server side
* if an id is given and already associated to a non deleted doc, a conflict "doc_exists" must be returned
* if the header `x-barrel-is-upsert: true`is given, even if a doc already exists, the winning revision will be overridden (like a put)

* PUT /<dbs>/docs/<id>

- if the document does not exist, return a 404 not found
- if ETag is given, the conflict is checked
- if no ETag given, the last winning revision will be updated

* DELETE /<dbs>/docs/<id>

- if the document does not exist, return a 404 not found
- if ETag is given, the conflict is checked
- if no ETag given, the last winning revision will be marked as deleted

* GET  /<dbs>/docs/<id> now return all the metadatain the<<"_meta">>  object property:

```json
{
  "id": "someid",
  ...
  "_meta": {
       "rev": "revision id",
       "rid": "resource id",
       "deleted": "true"
  }
}
```

> The revision ID is also returned in the ETag header
> We should ignore the deleted member if it's false.

* GET  /<dbs>/docs like for a doc all the  metadata data are in a "_meta" object

* HEAD /<dbs>/docs/docid should return the revision as an ETagg header if the doc exists.

**Comment by benoitc** [comment]
merged in latest master
